# Generated by Django 3.2.4 on 2021-09-12 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Organization Id')),
                ('organization_name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('organization_email_id', models.EmailField(blank=True, max_length=100, verbose_name='Email id')),
                ('organization_phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+250123456789'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,15}$'), django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)], verbose_name='Phone Number')),
                ('organization_logo_image', models.CharField(blank=True, max_length=255, verbose_name='Logo')),
                ('organization_created_at', models.IntegerField(default=0, verbose_name='Created At')),
                ('organization_created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('organization_updated_at', models.IntegerField(default=0, verbose_name='Updated At')),
                ('organization_updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('organization_status', models.IntegerField(default=1, verbose_name='Status')),
            ],
        ),
    ]
