# Generated by Django 4.0.2 on 2022-04-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets_external',
            name='ticket_card_response',
            field=models.TextField(blank=True, verbose_name='Card Response'),
        ),
        migrations.AlterField(
            model_name='tickets_external',
            name='ticket_card_transaction_status',
            field=models.TextField(blank=True, verbose_name='Card Transaction Status'),
        ),
    ]
